disabled_rules:
  - trailing_whitespace
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - force_unwrapping
  - implicitly_unwrapped_optional
  - redundant_nil_coalescing
  - private_outlet
  - private_action
  - yoda_condition
included:
  - ExpensesTracker
excluded:
  - Carthage
  - Pods
line_length: 200
file_length:
  warning: 500
  error: 1200
type_body_length:
  warning: 300
  error: 500
type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
identifier_name:
  min_length:
    error: 3
  excluded:
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode"
